# Generated by Django 4.1.3 on 2022-11-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_examen_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='idProfesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.profesor'),
            preserve_default=False,
        ),
    ]
