# Generated by Django 4.1.3 on 2022-11-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_salon_idprofesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_fecha', models.DateTimeField()),
                ('curso', models.CharField(max_length=30)),
                ('evaluador', models.CharField(max_length=30)),
                ('tema_proyecto', models.CharField(max_length=100)),
                ('numero_grupos', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='OrderedProy',
            fields=[
            ],
            options={
                'ordering': ['tema_proyecto'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.proyecto',),
        ),
    ]
