# Generated by Django 4.1.3 on 2022-11-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_profesor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='numero_grupos',
            field=models.IntegerField(),
        ),
    ]
