# Generated by Django 4.1.3 on 2022-12-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_proyecto_numero_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='salario',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
